# Generated by Django 3.0.6 on 2020-05-16 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ms_price', models.IntegerField()),
                ('ls_price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non Veg')], max_length=8)),
                ('item_image', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_reviews', models.ManyToManyField(to='reviews.ItemReview')),
                ('ratings', models.ManyToManyField(to='reviews.ItemRating')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium')], max_length=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemInventory')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('validity', models.DateTimeField()),
                ('items', models.ManyToManyField(to='inventory.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ContactDetail')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Address')),
                ('order_items', models.ManyToManyField(to='inventory.OrderItem')),
            ],
        ),
    ]
