# Generated by Django 3.0.6 on 2020-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200516_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='inventory.ItemInventory'),
        ),
    ]
